// export const CHANGE_CLASS = 'CHANGE_CLASS'
// export const CHANGE_EMAIL = 'CHANGE_EMAIL'
// export const CHANGE_COUNT = 'CHANGE_COUNT'
// export const WORK_LIST = 'WORK_LIST'
// export const CHANGE_DATA = 'CHANGE_DATA'
// export const GET_USER = 'GET_USER'
// export const REQUEST_DATA = 'REQUEST_DATA'
// export const IS_CHECK = 'IS_CHECK'
